core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='main_page')),
    path('wydarzenia/', include('website.urls', namespace='events_page'))
    # path('<str:name>/', dynamic_lookup_view, name=)

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "naBalety Admin"
admin.site.site_title = "naBalety Panel Administratora"
admin.site.index_title = "Site management"

website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('wydarzenia/', views.events_page, name='events_page'),
    path('<slug:slug>/', views.event_details, name='event_details'),
    path('bilet/<str:ticket_id>/', views.ticket_details_by_id, name='ticket_by_id'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}naBalety{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">naBalety</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/wydarzenia/">Wydarzenia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Informacje i kontakt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Panel logowania</a>
                        </li>
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "website:main_page" %}">All</a></li>
                                {% for e in events %}
                                <li {% if category.slug == e.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ e.get_absolute_url }}">{{ e.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li> -->
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

templates/events.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Wydarzenia{% endblock %}
{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">Wydarzenia</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for event in events %}
        {% if event.visible == True %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ event.banner.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ event.get_absolute_url }}">{{ event.name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{event.event_date_time}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}naBalety - strona główna{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
          etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Make an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Books</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for event in events %}
        {% if event.visible == True %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ event.banner.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ event.get_absolute_url }}">{{ event.name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{event.event_date_time}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}